# Stage 1: Dependencies
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./
RUN npm ci

# Stage 2: Builder
FROM node:20-alpine AS builder
WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build args vindos do EasyPanel
ARG NEXT_PUBLIC_SITE_NAME
ARG NEXT_PUBLIC_SITE_DESCRIPTION
ARG NEXT_PUBLIC_KEYWORDS
ARG NEXT_PUBLIC_AUTHOR
ARG NEXT_PUBLIC_THEME
ARG NEXT_PUBLIC_BRAND
ARG NEXT_PUBLIC_PRODUCT
ARG NEXT_PUBLIC_REGION_ZIPCODE
ARG NEXT_PUBLIC_REGION_NAME
ARG NEXT_PUBLIC_ZIPCODE_API_URL
ARG NEXT_PUBLIC_SCHEDULE_URL
ARG NEXT_PUBLIC_COMPANY_PHONE
ARG NEXT_PUBLIC_COMPANY_WHATSAPP
ARG NEXT_PUBLIC_ID_EMPRESA

# Exporta como ENV para o next build
ENV NEXT_PUBLIC_SITE_NAME=${NEXT_PUBLIC_SITE_NAME}
ENV NEXT_PUBLIC_SITE_DESCRIPTION=${NEXT_PUBLIC_SITE_DESCRIPTION}
ENV NEXT_PUBLIC_KEYWORDS=${NEXT_PUBLIC_KEYWORDS}
ENV NEXT_PUBLIC_AUTHOR=${NEXT_PUBLIC_AUTHOR}
ENV NEXT_PUBLIC_THEME=${NEXT_PUBLIC_THEME}
ENV NEXT_PUBLIC_BRAND=${NEXT_PUBLIC_BRAND}
ENV NEXT_PUBLIC_PRODUCT=${NEXT_PUBLIC_PRODUCT}
ENV NEXT_PUBLIC_REGION_ZIPCODE=${NEXT_PUBLIC_REGION_ZIPCODE}
ENV NEXT_PUBLIC_REGION_NAME=${NEXT_PUBLIC_REGION_NAME}
ENV NEXT_PUBLIC_ZIPCODE_API_URL=${NEXT_PUBLIC_ZIPCODE_API_URL}
ENV NEXT_PUBLIC_SCHEDULE_URL=${NEXT_PUBLIC_SCHEDULE_URL}
ENV NEXT_PUBLIC_COMPANY_PHONE=${NEXT_PUBLIC_COMPANY_PHONE}
ENV NEXT_PUBLIC_COMPANY_WHATSAPP=${NEXT_PUBLIC_COMPANY_WHATSAPP}
ENV NEXT_PUBLIC_ID_EMPRESA=${NEXT_PUBLIC_ID_EMPRESA}

# Set environment variable for build
ENV NEXT_TELEMETRY_DISABLED 1

# Build the application
RUN npm run build

# Stage 3: Runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy necessary files from builder
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Create cache directory and set permissions
RUN mkdir -p .next/cache && \
    chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]

